AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Max: 300

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 20
