#!/usr/bin/env ruby
# frozen_string_literal: true

require "webrick"
require "stringio"
require_relative "../web/server"

port = ENV.fetch("PORT", 9292).to_i
app = EmtbusRtt::Web::Server.new

puts "\n🚌 EMT Madrid Bus Tracker"
puts "=" * 40
puts "Starting server on http://localhost:#{port}"
puts "Press Ctrl+C to stop\n\n"

server = WEBrick::HTTPServer.new(
  Port: port,
  Logger: WEBrick::Log.new($stderr, WEBrick::Log::INFO),
  AccessLog: [[File.open(File::NULL, "w"), WEBrick::AccessLog::COMMON_LOG_FORMAT]]
)

server.mount_proc "/" do |req, res|
  env = {
    "REQUEST_METHOD" => req.request_method,
    "SCRIPT_NAME" => "",
    "PATH_INFO" => req.path,
    "QUERY_STRING" => req.query_string || "",
    "SERVER_NAME" => req.host,
    "SERVER_PORT" => req.port.to_s,
    "rack.version" => [1, 3],
    "rack.url_scheme" => "http",
    "rack.input" => StringIO.new(req.body || ""),
    "rack.errors" => $stderr,
    "rack.multithread" => true,
    "rack.multiprocess" => false,
    "rack.run_once" => false
  }

  # Add HTTP headers
  req.each { |key, value| env["HTTP_#{key.upcase.tr("-", "_")}"] = value }

  status, headers, body = app.call(env)

  res.status = status
  headers.each { |key, value| res[key] = value }
  body.each { |chunk| res.body << chunk }
end

trap("INT") { server.shutdown }
trap("TERM") { server.shutdown }

server.start
